### ISSUE TITLE
is there any implementation to useNF2 whit python 

### ISSUE THREAD

**Issue by MirkoPerrone** [nanofury/NanoFury#3]
Hi i'm wondering if there is any kind of implementation of NF2 for python ... Im asking couse i want tu use nf2 in my python program but i can not know how to access to NF2 , is there any API or Driver  o Library to use in python or any other proramming languages

**Comment by vstrinski** [comment]
Can you please elaborate on "how to access NF2"? Are you looking for low-level access to the bitfury chips? Or something else?
If you want low-level access you can use the provided sample C code which is part of the project. This code was used in one form or another as the driver that's embedded in bfgminer and cgminer.
Or if you are looking for obtaining stats and other similar high-level access to the mining software then you can use the API provided by bfgminer or cgminer or whichever software you use.
Let me know please if this answered your question.
