### ISSUE TITLE
Some help 

### ISSUE THREAD

**Issue by PEVN** [nanofury/NanoFury#4]
After reading the thread I have two questions...
,1) can I build the H and M boards along with a power supply, connect them together and have an operational miner?
2) Would these schematics work with the new bitfury chip?

**Comment by vstrinski** [comment]
Hello,

you've probably located the wrong project - this one doesn't have "H and M boards" (and to be honest I am not sure which boards you are referring to).

As for the second part - the schematics were meant to work with a very specific chip. They will not work with another chip.
