### ISSUE TITLE
Help on Building 

### ISSUE THREAD

**Issue by yacobtsige** [nanofury/NanoFury#5]
hi guys im trying this project with my friends , and I was wondering how I can make it im new to this and I was hoping if you guys could show me

**Comment by MirkoPerrone** [comment]
Ehy Hi, what it is about ? I can help if it is an interesting project.
Keep me posted, bye 👍

**Comment by yacobtsige** [comment]
well the hole project is to show you how to build your own usb miner , I couldn't find a bitfury asic chip I contacted them but they said 50000 chips is min. order any ideas

**Comment by Vallerik** [comment]
Hey! I join the question, where can you buy an ASIC chip?

**Comment by yacobtsige** [comment]
Well i asked that question a long while ago and found out 2 things 
1.finding the chips they use is really hard and even if you find it they might not give you the datasheet of their ASIC chips
2. Their greedy they make millions selling the stuff and they hate the idea of losing profit so they don't give out any info 

but if you are committed then your options are either to buy an old asic miner break it apart and start experimenting or order 50Kchips from bitfury and ask them to help you . They state that they will help your hardware development but either way i personally abandoned all hopes on this but i hope you find something useful and interesting also check on alibaba their shady but some sell old asic chips good luck

**Comment by Vallerik** [comment]
It's a shame that it turns out this way .. I want to make my own miner, are there any similar projects? Which can be repeated? Another Usb miner project?

**Comment by nanofury** [comment]
Hello, first - I applaud your desire to give this project a try. However, keep in mind that it was developed so long ago that even if you could find the chips and everything it would still not be a viable product.

Then, at the root of the project are the Bitfury chips. They were hard to get even back then.

They are no longer available (and haven't been available for many years). They were efficient back in the days, but with the bitcoin difficulty jumping multiple orders of magnitude the chips are no longer feasible.
You might find other and more modern chips, but they would almost certainly require a completely new design.

However, if you do find some other chips that you would like to experiment with - this project could serve as a good base design. Feel free to experiment!

Good luck!
