### ISSUE TITLE
Bitfury chip

### ISSUE THREAD

**Issue by NicoGas2001** [nanofury/NanoFury#6]
Hi, my name is Niccolò
Where can i find the Bitfury QFN48 chip?
Can it be replaced by another chip on te market?
I have found the Bm1387 antminer chips,but I don't think they can be implemented without making changes to the pcb, can you say something about it?

Tanks @nanofury

**Comment by BastelPichi** [comment]
This project is old, 2ghs is nothing nowadays...
Different chip takes redesign of course

**Comment by vstrinski** [comment]
BastelPichi is correct - the chip is (beyond) obsolete. It was last manufactured almost 10 years ago. There is no new supply of those chips.
Any new chip would require a new design.
